channel:
    resource: "@ChannelBundle/Resources/config/routing.yml"
    prefix:   /

media_media:
    resource: "@MediaMediaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
